### PR TITLE
Upgrading emotion from 9 to 11

### PR DESCRIPTION
**Pull request by Dezzymei**
So as to fix https://github.com/segmentio/consent-manager/issues/135 with the warnings.

### CODE REVIEW

**Comment by Dezzymei** [comment]
It failed only on the build size... I can work on making this smaller I guess.

**Comment by pooyaj** [comment]
strange, wonder why the size is doubled 🤔

**Comment by pooyaj** [comment]
@Dezzymei would you mind increasing the size limit in your PR so that the build passes, and then I'll merge this in.

**Comment by Dezzymei** [comment]
I'll look to work on this today.

**Comment by Dezzymei** [comment]
Done!

**Review by pooyaj — APPROVED** [review]

**Comment by pooyaj** [comment]
@Dezzymei looks like the recent commits removed all the changes. Now it is just the size limit change

**Comment by Dezzymei** [comment]
Oops - reverted the revert (don't know why I did that!)

**Review by edsonjab — APPROVED** [review]
The upgrade works, all the components shows correctly

**Pull request merged**
