### PR TITLE
Sync fork into official version

### PR DESCRIPTION
**Pull request by dmitry-zaets**
# This PR introduces:
- Fix https://github.com/segmentio/consent-manager/issues/104
- A possibility to add default buttons to accept/deny cookies via `bannerActionsBlock`
- A possibility to add custom buttons block via `bannerActionsBlock`
- Hide Clone button via `bannerHideCloseButton`
- Fix the dialog on iPhone
- Add option to show banner as modal
- Use only `loadsh-es` and remove `lodash` package and include only used functions instead of the whole package (reduce the final bundle size)
- Update webpack CLI

### A possibility to add default buttons to accept/deny cookies via `bannerActionsBlock` 

| Default Buttons | Without Close Button |
|---|---|
| image | image|
### A possibility to add custom buttons block via `bannerActionsBlock`

| Custom Buttons | Without Close Button |
|---|---|
| image|image |

Mobile:
| Default Buttons | Without Close Button | Custom Buttons | Without Close Button |
|---|---|---|---|
| image | image | image | image |

### Fix the dialog on iPhone

| Before | After |
|---|---|
| 4437EEAD-15AE-406D-9CEC-DC3CFF10CA22 | B117A412-708B-48B3-9161-87A0C445887E | 

### Banner as Modal

image

### CODE REVIEW

**Review by pooyaj — APPROVED** [review]
@dmitry-zaets amazing work 🙌

**Comment by camwest** [comment]
@dmitry-zaets what's the ETA on cutting this release? Very excited!

**Comment by felipe-najson-ntf** [comment]
Hi @camwest! We will be working this week to publish the new version of the library.

Segment team.

**Comment by pooyaj** [comment]
@camwest @felipe-najson-ntf `5.3.0` is now available on npm 🎉

**Pull request merged**
