### PR TITLE
Customizable messages

### PR DESCRIPTION
**Pull request by Walkeryr**
Hi, we are using your library in [Zava](https://www.zavamed.com/uk/). We found it very useful as we are using Segment, but we had requirement to customise all the text messages inside consent manager. We have website in multiple languages German, French, English. So, we've added support to customise any text in UI of consent-manager. 

I've added additional parameter `translationMessages` in the list of options to configure `consent-manager`. I didn't move `bannerContent` and other options into it to avoid braking changes. That can be joined together in major update. I'm providing fallback messages in file `default-messages.js`.

What do you think? Would you consider adding localisation support to consent-manager?

### CODE REVIEW

**Comment by Walkeryr** [comment]
Hey guys! Did you have any plans for localisation support? Is it possible to do in future?

**Comment by nettofarah** [comment]
hey, @Walkeryr.
I really like where this is going.

I'm thinking we might be able to customize the implementation a bit further though.
How about we try something like:

```javascript
window.consentManagerConfig.locales = {
  'pt-BR': {...},
  'pt-PT': {...}
}
```

And then we could have the consent manager maybe lookup some of these messages?

**Comment by Walkeryr** [comment]
Yeah, nice one! I'd try to implement it.

**Comment by omairvaiyani** [comment]
@Walkeryr would you be able to give a really quick update on this PR, I'd be happy to help get it over the line.

**Comment by Walkeryr** [comment]
Hi @omairvaiyani, yeah, not much progress, I was catching up with latests changes in master branch.

**Comment by Walkeryr** [comment]
@nettofarah Yeah, interesting idea, then we just need to pass locale code during consent-manager initialisation. However in this case we can't use React elements inside translation messages and quite often adding link or paragraph is required.

We could store plain markup in this global variable, but then we would need to use: `dangerouslySetInnerHTML`, but I'd use it as a last resort.

Is having a global variable with translations is hard requirement?

**Comment by jonathan3692bf** [comment]
I'm going to try to bring this PR back from the dead by:
1. Translating @Walkeryr 's work to the lasted commit on master (which means typescript)
2. Trying to incorporate @nettofarah 's suggestion that we look into a window loaded translation dictionary.

Hopefully I can have something for y'all be the end of the week.

**Comment by nd4p90x** [comment]
Closing due to age

**Pull request closed without merging**
